services:
  - type: web
    name: navibus-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn navibus_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
