services:
  - type: web
    name: navibus-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && (python manage.py load_production_data --file=production_data.json || echo 'Data loading failed, will load manually')"
    startCommand: "gunicorn navibus_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
