# Generated by Django 5.2.1 on 2025-06-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stop_latitude_alter_stop_longitude'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='distance_from_start',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='fare_from_prev',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='is_major_stop',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(default='In Service', max_length=20),
        ),
        migrations.AddField(
            model_name='busroute',
            name='source_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_identifier',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='routes.busroute'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='route_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='repeat_pattern',
            field=models.CharField(blank=True, default='Daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'stop'], name='routes_rout_route_i_f08a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['stop'], name='routes_rout_stop_id_8aa5a2_idx'),
        ),
    ]
