# Generated by Django 5.2.1 on 2025-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_busroute_fare_inr_busroute_first_bus_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroute',
            old_name='frequency_minutes',
            new_name='average_frequency_minutes',
        ),
        migrations.RenameField(
            model_name='busroute',
            old_name='first_bus_time',
            new_name='first_bus_time_sunday',
        ),
        migrations.RenameField(
            model_name='busroute',
            old_name='last_bus_time',
            new_name='first_bus_time_weekday',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='fare_inr',
        ),
        migrations.AddField(
            model_name='busroute',
            name='average_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='last_bus_time_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='last_bus_time_weekday',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
