# Generated by Django 5.1.2 on 2025-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_rename_frequency_minutes_busroute_average_frequency_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='average_frequency_minutes_sunday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
