# Generated by Django 5.1.2 on 2025-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
